name: weather_news_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.3
  dio:
  flutter_riverpod:
  freezed_annotation:
  cached_network_image:
  statusbarz: ^1.0.13
  google_fonts:
  url_launcher: ^6.1.10
  dio_http_cache:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  freezed:

flutter:

  uses-material-design: true

  assets:
    - assets/img_not_found.png

